//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenteVenta
    {
        public string ClaveVenta { get; set; }
        public long IdVentaCinestar { get; set; }
    
        public virtual VentaCinestar VentaCinestar { get; set; }
    }
}
