//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentTransactions
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public string OrderId { get; set; }
        public string Key { get; set; }
        public string Complex { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int Retries { get; set; }
        public int State { get; set; }
        public string LastResponse { get; set; }
        public string LanguageId { get; set; }
        public string SaleInformation { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<int> CinestarSaleState { get; set; }
    }
}
