//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockbusterMovies
    {
        public int Id { get; set; }
        public byte Online { get; set; }
        public string Title { get; set; }
        public int CodMovie { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> Premiere { get; set; }
    }
}
