//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cache_CopiasPelicula
    {
        public int CodPelicula { get; set; }
        public int CodCopia { get; set; }
        public int IdTecnologia { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> CodIdioma { get; set; }
        public bool Subtitulada { get; set; }
        public bool Doblada { get; set; }
    }
}
