//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cache_Lenguajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cache_Lenguajes()
        {
            this.Cache_Peliculas = new HashSet<Cache_Peliculas>();
        }
    
        public int CodLenguaje { get; set; }
        public string NomLenguaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cache_Peliculas> Cache_Peliculas { get; set; }
    }
}
