//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cache_Productos
    {
        public int CodProducto { get; set; }
        public int CodComplejo { get; set; }
        public string NomProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public short Posicion { get; set; }
        public string NombreArchivo { get; set; }
    
        public virtual Complejos Complejos { get; set; }
    }
}
