//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cache_Cinesemanas
    {
        public int CodComplejo { get; set; }
        public System.DateTime Desde { get; set; }
        public System.DateTime Hasta { get; set; }
    
        public virtual Complejos Complejos { get; set; }
    }
}
