//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cache_Salas
    {
        public short CodSala { get; set; }
        public string NomSala { get; set; }
        public int CodTipoSala { get; set; }
        public string NomTipoSala { get; set; }
        public int CodComplejo { get; set; }
    
        public virtual Complejos Complejos { get; set; }
    }
}
