//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_Loyalty
    {
        public decimal CodCliente { get; set; }
        public string NomCliente { get; set; }
        public string Apellido { get; set; }
        public string TelCliente { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public string Passw { get; set; }
        public Nullable<System.DateTime> FecNac { get; set; }
        public Nullable<System.DateTime> FecIngreso { get; set; }
        public Nullable<decimal> CreadoDesde { get; set; }
    }
}
