//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplexImages
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public string Imagebase64 { get; set; }
        public Nullable<int> ComplexId { get; set; }
    }
}
