//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplejosAux
    {
        public int CodComplejo { get; set; }
        public int CodTerminal { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string PassEmail { get; set; }
        public string SMTPServer { get; set; }
        public string PaymentService { get; set; }
        public string EnableSSL { get; set; }
        public string PortNumber { get; set; }
        public string GoogleAnalytics { get; set; }
        public bool allow_sale { get; set; }
        public bool allow_concessionsale { get; set; }
    }
}
