//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complejos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complejos()
        {
            this.Cache_Funciones = new HashSet<Cache_Funciones>();
            this.Cache_GruposSemana = new HashSet<Cache_GruposSemana>();
            this.Cache_KeyLayouts = new HashSet<Cache_KeyLayouts>();
            this.Cache_Productos = new HashSet<Cache_Productos>();
            this.Cache_Salas = new HashSet<Cache_Salas>();
            this.ImagenesComplejos = new HashSet<ImagenesComplejos>();
            this.Prom_Promotions = new HashSet<Prom_Promotions>();
        }
    
        public int CodComplejo { get; set; }
        public string NomComplejo { get; set; }
    
        public virtual Cache_Cinesemanas Cache_Cinesemanas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cache_Funciones> Cache_Funciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cache_GruposSemana> Cache_GruposSemana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cache_KeyLayouts> Cache_KeyLayouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cache_Productos> Cache_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cache_Salas> Cache_Salas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesComplejos> ImagenesComplejos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prom_Promotions> Prom_Promotions { get; set; }
    }
}
