//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contents
    {
        public long id { get; set; }
        public string english_title { get; set; }
        public string spanish_title { get; set; }
        public string english_content { get; set; }
        public string spanish_content { get; set; }
        public Nullable<byte> include_picture { get; set; }
        public byte[] picture { get; set; }
        public long id_section { get; set; }
        public Nullable<byte> online { get; set; }
        public bool in_home { get; set; }
        public string imagebase64 { get; set; }
    
        public virtual web_site_sections web_site_sections { get; set; }
    }
}
