//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSWebNuevoEntities : DbContext
    {
        public CSWebNuevoEntities()
            : base("name=CSWebNuevoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AgenteVenta> AgenteVenta { get; set; }
        public virtual DbSet<AgentTransactions> AgentTransactions { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<banners> banners { get; set; }
        public virtual DbSet<Barcodes> Barcodes { get; set; }
        public virtual DbSet<BlockbusterMovies> BlockbusterMovies { get; set; }
        public virtual DbSet<Cache_Actores> Cache_Actores { get; set; }
        public virtual DbSet<Cache_Cinesemanas> Cache_Cinesemanas { get; set; }
        public virtual DbSet<Cache_Clasificaciones> Cache_Clasificaciones { get; set; }
        public virtual DbSet<Cache_ComplejosGeo> Cache_ComplejosGeo { get; set; }
        public virtual DbSet<Cache_Directores> Cache_Directores { get; set; }
        public virtual DbSet<Cache_Funciones> Cache_Funciones { get; set; }
        public virtual DbSet<Cache_Generos> Cache_Generos { get; set; }
        public virtual DbSet<Cache_GruposSemana> Cache_GruposSemana { get; set; }
        public virtual DbSet<Cache_KeyLayouts> Cache_KeyLayouts { get; set; }
        public virtual DbSet<Cache_Lenguajes> Cache_Lenguajes { get; set; }
        public virtual DbSet<Cache_Peliculas> Cache_Peliculas { get; set; }
        public virtual DbSet<Cache_Productos> Cache_Productos { get; set; }
        public virtual DbSet<Cache_Salas> Cache_Salas { get; set; }
        public virtual DbSet<Cache_Tecnologias> Cache_Tecnologias { get; set; }
        public virtual DbSet<Caches> Caches { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Clients_Loyalty> Clients_Loyalty { get; set; }
        public virtual DbSet<Complejos> Complejos { get; set; }
        public virtual DbSet<ComplejosAux> ComplejosAux { get; set; }
        public virtual DbSet<Complex_Options> Complex_Options { get; set; }
        public virtual DbSet<ComplexImages> ComplexImages { get; set; }
        public virtual DbSet<ComprasInfo> ComprasInfo { get; set; }
        public virtual DbSet<contents> contents { get; set; }
        public virtual DbSet<DeviceImageSettings> DeviceImageSettings { get; set; }
        public virtual DbSet<GeneralEmail> GeneralEmail { get; set; }
        public virtual DbSet<HomePageFooterItems> HomePageFooterItems { get; set; }
        public virtual DbSet<HomePopups> HomePopups { get; set; }
        public virtual DbSet<ImagenesComplejos> ImagenesComplejos { get; set; }
        public virtual DbSet<languages> languages { get; set; }
        public virtual DbSet<LogAdmin> LogAdmin { get; set; }
        public virtual DbSet<LogAgent> LogAgent { get; set; }
        public virtual DbSet<LogWeb> LogWeb { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<PaymentCards> PaymentCards { get; set; }
        public virtual DbSet<PaymentServices> PaymentServices { get; set; }
        public virtual DbSet<Poster> Poster { get; set; }
        public virtual DbSet<Prom_CondPaymentsCards> Prom_CondPaymentsCards { get; set; }
        public virtual DbSet<Prom_CondPaymentsServices> Prom_CondPaymentsServices { get; set; }
        public virtual DbSet<Prom_PromConditions> Prom_PromConditions { get; set; }
        public virtual DbSet<Prom_Promotions> Prom_Promotions { get; set; }
        public virtual DbSet<Prom_TicketCondition> Prom_TicketCondition { get; set; }
        public virtual DbSet<Recomendadas> Recomendadas { get; set; }
        public virtual DbSet<Registro_Links> Registro_Links { get; set; }
        public virtual DbSet<SectionGroups> SectionGroups { get; set; }
        public virtual DbSet<sliders> sliders { get; set; }
        public virtual DbSet<Statistic_Event> Statistic_Event { get; set; }
        public virtual DbSet<Statistic_Log> Statistic_Log { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<templates> templates { get; set; }
        public virtual DbSet<Theaters> Theaters { get; set; }
        public virtual DbSet<translations> translations { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<VentaCinestar> VentaCinestar { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<web_site_options> web_site_options { get; set; }
        public virtual DbSet<web_site_sections> web_site_sections { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Cache_CopiasPelicula> Cache_CopiasPelicula { get; set; }
    }
}
