//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceImageSettings
    {
        public int Id { get; set; }
        public string ImageTypeCode { get; set; }
        public Nullable<int> DesktopWidth { get; set; }
        public Nullable<int> TabletWidth { get; set; }
        public Nullable<int> SmartphoneWidth { get; set; }
        public Nullable<int> CellphoneWidth { get; set; }
    }
}
