//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogWeb
    {
        public long Id { get; set; }
        public int TipoError { get; set; }
        public string Pagina { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaServidor { get; set; }
        public string Aplicacion { get; set; }
        public string Mensaje { get; set; }
    }
}
