//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCards
    {
        public int idAgent { get; set; }
        public int idCard { get; set; }
        public string name { get; set; }
        public long theaterId { get; set; }
    }
}
