//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentServices
    {
        public long IdAgente { get; set; }
        public long TheaterId { get; set; }
        public string AgentUrl { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IconUrl { get; set; }
        public bool Enabled { get; set; }
        public Nullable<bool> UseCreditCard { get; set; }
        public Nullable<int> codTerminal { get; set; }
        public Nullable<int> codUsuario { get; set; }
    }
}
