//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prom_CondPaymentsCards
    {
        public int Id { get; set; }
        public Nullable<int> IdCondition { get; set; }
        public Nullable<long> IdAgent { get; set; }
        public Nullable<long> IdTheater { get; set; }
        public Nullable<int> IdCard { get; set; }
    
        public virtual Prom_TicketCondition Prom_TicketCondition { get; set; }
    }
}
