//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prom_TicketCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prom_TicketCondition()
        {
            this.Prom_CondPaymentsCards = new HashSet<Prom_CondPaymentsCards>();
            this.Prom_CondPaymentsServices = new HashSet<Prom_CondPaymentsServices>();
            this.Prom_PromConditions = new HashSet<Prom_PromConditions>();
        }
    
        public int IdCondition { get; set; }
        public Nullable<int> IdTicketType { get; set; }
        public string NameTicketType { get; set; }
        public string CountTickets { get; set; }
        public Nullable<int> MaxAmount { get; set; }
        public string WsPlatform { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prom_CondPaymentsCards> Prom_CondPaymentsCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prom_CondPaymentsServices> Prom_CondPaymentsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prom_PromConditions> Prom_PromConditions { get; set; }
    }
}
