//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sliders
    {
        public long id { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> slider_order { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string imagebase64 { get; set; }
        public Nullable<bool> AllowUrl { get; set; }
        public string Url { get; set; }
        public string filename { get; set; }
    }
}
