//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theaters
    {
        public long id { get; set; }
        public string name { get; set; }
        public long id_ciudad { get; set; }
        public string web_service_url { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string zip_code { get; set; }
        public Nullable<long> TheaterGroupId { get; set; }
        public Nullable<long> TheaterId { get; set; }
        public string SMTP_Server { get; set; }
        public string Account_Email { get; set; }
        public string Pwd_Account_Email { get; set; }
        public byte AllowLoyalty { get; set; }
        public string web_service_loyalty { get; set; }
        public byte AllowWebSales { get; set; }
        public string web_service_trans { get; set; }
        public string WorkStation { get; set; }
        public string WorkStationIpAddress { get; set; }
        public string PaymentServices { get; set; }
        public int MaxSales { get; set; }
        public Nullable<int> seatsGuardNum { get; set; }
        public Nullable<int> seatsGuardNotNum { get; set; }
        public Nullable<bool> usePercNum { get; set; }
        public Nullable<bool> usePercNotNum { get; set; }
        public string twitterAccount { get; set; }
        public Nullable<bool> twitterButton { get; set; }
        public Nullable<bool> facebookButton { get; set; }
        public string facebookAccount { get; set; }
        public string barcode { get; set; }
        public Nullable<bool> useQuickSale { get; set; }
        public byte AllowReserves { get; set; }
        public string description { get; set; }
    
        public virtual Barcodes Barcodes { get; set; }
    }
}
