//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class translations
    {
        public System.Guid Id { get; set; }
        public string literal { get; set; }
        public long id_language { get; set; }
        public string id_element { get; set; }
        public string Description { get; set; }
    }
}
