//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string usuario_login { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_password { get; set; }
        public string usuario_email { get; set; }
        public long usuario_id { get; set; }
    }
}
