//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.ComprasInfo = new HashSet<ComprasInfo>();
        }
    
        public long Id { get; set; }
        public long TheaterId { get; set; }
        public bool Pendiente { get; set; }
        public string Xml { get; set; }
        public System.DateTime FechaInsert { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int Intentos { get; set; }
        public string ClaveVenta { get; set; }
        public int CinestarSaleState { get; set; }
        public Nullable<int> SaleEmailState { get; set; }
        public Nullable<bool> ReminderSend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasInfo> ComprasInfo { get; set; }
    }
}
