//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaCinestar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentaCinestar()
        {
            this.AgenteVenta = new HashSet<AgenteVenta>();
        }
    
        public long Id { get; set; }
        public string ClaveCinestar { get; set; }
        public string Carrito { get; set; }
        public int SessionTrans { get; set; }
        public System.DateTime Fecha { get; set; }
        public string IP { get; set; }
        public long TheaterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgenteVenta> AgenteVenta { get; set; }
    }
}
