//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_site_sections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public web_site_sections()
        {
            this.contents = new HashSet<contents>();
        }
    
        public long id { get; set; }
        public string title_section_spanish { get; set; }
        public string title_section_english { get; set; }
        public Nullable<byte> activated { get; set; }
        public Nullable<bool> in_columns { get; set; }
        public Nullable<byte> columns { get; set; }
        public Nullable<System.Guid> SectionGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contents> contents { get; set; }
    }
}
