//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCache.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_site_options
    {
        public long id { get; set; }
        public string web_site_title { get; set; }
        public string footer { get; set; }
        public byte[] header_image { get; set; }
        public long template_id { get; set; }
        public Nullable<long> main_language_id { get; set; }
        public Nullable<long> second_language_id { get; set; }
        public string footer2 { get; set; }
        public byte[] backgroundImage { get; set; }
        public string backgroundRepeat { get; set; }
        public bool headerIsUpdated { get; set; }
        public bool useRss { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string youtube { get; set; }
        public bool allow_reserve { get; set; }
        public bool allow_sale { get; set; }
        public int theatreGroup { get; set; }
        public byte[] bottomImage { get; set; }
        public string wsinfo { get; set; }
        public string wstrans { get; set; }
        public string wsloyalty { get; set; }
        public Nullable<bool> show_TandC { get; set; }
        public Nullable<bool> detailFee { get; set; }
        public Nullable<bool> menuCinema { get; set; }
        public Nullable<bool> menuPresale { get; set; }
        public Nullable<bool> menuComing { get; set; }
        public Nullable<bool> menuContact { get; set; }
        public Nullable<bool> menuLogin { get; set; }
        public Nullable<bool> allow_fastsale { get; set; }
        public string wsPromos { get; set; }
        public string wsPromosUser { get; set; }
        public string wsPromosPassword { get; set; }
        public Nullable<int> submitEntries { get; set; }
        public Nullable<int> reminderTime { get; set; }
    }
}
